/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openfactorybeans.citynet.desktop.menu;

/**
 *
 * @author Jose
 */
public class DesktopMain extends javax.swing.JFrame {

    /**
     * Creates new form DesktopMain
     */
    public DesktopMain() {
        initComponents();
        //setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuStart = new javax.swing.JMenu();
        jMenuStartExit = new javax.swing.JMenuItem();
        jMenuUsers = new javax.swing.JMenu();
        jMenuUserAdd = new javax.swing.JMenuItem();
        jMenuUsersModify = new javax.swing.JMenuItem();
        jMenuUsersDelete = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuUsersList = new javax.swing.JMenuItem();
        jMenuUsersListRol = new javax.swing.JMenuItem();
        jMenuContainers = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        jMenuStart.setText("Inici");

        jMenuStartExit.setText("Sortir");
        jMenuStartExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuStartExitActionPerformed(evt);
            }
        });
        jMenuStart.add(jMenuStartExit);

        jMenuBar1.add(jMenuStart);

        jMenuUsers.setText("Usuaris");
        jMenuUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsersActionPerformed(evt);
            }
        });

        jMenuUserAdd.setText("Afegir");
        jMenuUserAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUserAddActionPerformed(evt);
            }
        });
        jMenuUsers.add(jMenuUserAdd);

        jMenuUsersModify.setText("Modificar");
        jMenuUsers.add(jMenuUsersModify);

        jMenuUsersDelete.setText("Eliminar");
        jMenuUsers.add(jMenuUsersDelete);
        jMenuUsers.add(jSeparator1);

        jMenuUsersList.setText("Llistar usuaris");
        jMenuUsersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsersListActionPerformed(evt);
            }
        });
        jMenuUsers.add(jMenuUsersList);

        jMenuUsersListRol.setText("Llistar permisos");
        jMenuUsersListRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsersListRolActionPerformed(evt);
            }
        });
        jMenuUsers.add(jMenuUsersListRol);

        jMenuBar1.add(jMenuUsers);

        jMenuContainers.setText("Contenidors");
        jMenuBar1.add(jMenuContainers);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuStartExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuStartExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuStartExitActionPerformed

    private void jMenuUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuUsersActionPerformed

    private void jMenuUsersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsersListActionPerformed
        // TODO add your handling code here:
        UsersList usersList = new UsersList();
        this.jDesktop.add(usersList);
        usersList.setVisible(true);
    }//GEN-LAST:event_jMenuUsersListActionPerformed

    private void jMenuUsersListRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsersListRolActionPerformed
        // TODO add your handling code here:
        UsersListRols usersListRols = new UsersListRols();
        jDesktop.add(usersListRols);
        usersListRols.setVisible(true);
    }//GEN-LAST:event_jMenuUsersListRolActionPerformed

    private void jMenuUserAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUserAddActionPerformed
        // TODO add your handling code here:
        UserAdd userAdd = new UserAdd();
        jDesktop.add(userAdd);
        userAdd.setVisible(true);
    }//GEN-LAST:event_jMenuUserAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesktopMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuContainers;
    private javax.swing.JMenu jMenuStart;
    private javax.swing.JMenuItem jMenuStartExit;
    private javax.swing.JMenuItem jMenuUserAdd;
    private javax.swing.JMenu jMenuUsers;
    private javax.swing.JMenuItem jMenuUsersDelete;
    private javax.swing.JMenuItem jMenuUsersList;
    private javax.swing.JMenuItem jMenuUsersListRol;
    private javax.swing.JMenuItem jMenuUsersModify;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
