package com.openfactorybeans.citynet.desktop.forms;

import com.openfactorybeans.citynet.desktop.management.ContainersManagement;
import com.openfactorybeans.citynet.desktop.utils.JsonUtils;
import com.openfactorybeans.citynet.desktop.utils.TMContainer;
import javax.swing.JOptionPane;

/**
 * Formulari per eliminar un contenidor
 * 
 * @author Jose
 */
public class ContainerDelete extends javax.swing.JInternalFrame {
    
    //Declaració de les variables
    private String id;
    private TMContainer modelTable;
    private int selectedRow;
    
    //Variables per la connexió amb el servidor
    private String serverResponse;
    private String serverMessageError;
    private String serverMessageOK;
    

    /**
     * Creates new form ContainerDelete
     * 
     * @param id Identificador del contenidor a eliminar
     * @param type Type de contenidor
     * @param latitude Latitud per la seva ubicació
     * @param longitude Longitud per la seva ubicació
     * @param modelTable Model de la taula de contenidors
     * @param selectedRow Index de la fila seleccionada
     */
    public ContainerDelete(String id, String type, String latitude, String longitude, TMContainer modelTable, int selectedRow) {
        initComponents();
        
        btnCancel.requestFocus();
        
        this.id = id;
        this.modelTable = modelTable;
        this.selectedRow = selectedRow;
        
        lblContainerId.setText(id);
        lblContainerType.setText(type);
        lblContainerLatitude.setText(latitude);
        lblContainerLongitude.setText(longitude);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDetail = new javax.swing.JPanel();
        lblTitleContainerDelete = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblContainerId = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelContainerType = new javax.swing.JPanel();
        lblType = new javax.swing.JLabel();
        lblContainerType = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblLocation = new javax.swing.JLabel();
        lblLatitude = new javax.swing.JLabel();
        lblContainerLatitude = new javax.swing.JLabel();
        lblLongitude = new javax.swing.JLabel();
        lblContainerLongitude = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jPanelDetail.setPreferredSize(new java.awt.Dimension(390, 317));

        lblTitleContainerDelete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitleContainerDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleContainerDelete.setText("Eliminar contenidor");
        lblTitleContainerDelete.setPreferredSize(new java.awt.Dimension(0, 24));

        lblId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblId.setText("Identificador:");

        lblContainerId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContainerId.setForeground(new java.awt.Color(102, 0, 0));
        lblContainerId.setPreferredSize(new java.awt.Dimension(50, 19));

        lblType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblType.setText("Tipus de contenidor:");

        lblContainerType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContainerType.setForeground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanelContainerTypeLayout = new javax.swing.GroupLayout(jPanelContainerType);
        jPanelContainerType.setLayout(jPanelContainerTypeLayout);
        jPanelContainerTypeLayout.setHorizontalGroup(
            jPanelContainerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContainerType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContainerTypeLayout.setVerticalGroup(
            jPanelContainerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerTypeLayout.createSequentialGroup()
                .addGroup(jPanelContainerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(lblContainerType, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblLocation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLocation.setText("Ubicació");

        lblLatitude.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLatitude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLatitude.setText("Latitud");

        lblContainerLatitude.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContainerLatitude.setForeground(new java.awt.Color(102, 0, 0));
        lblContainerLatitude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblLongitude.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLongitude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLongitude.setText("Longitud");

        lblContainerLongitude.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContainerLongitude.setForeground(new java.awt.Color(102, 0, 0));
        lblContainerLongitude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelete.setText("Eliminar");
        btnDelete.setPreferredSize(new java.awt.Dimension(101, 35));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setText("Cancel·lar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(40, 40, 40))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDetailLayout = new javax.swing.GroupLayout(jPanelDetail);
        jPanelDetail.setLayout(jPanelDetailLayout);
        jPanelDetailLayout.setHorizontalGroup(
            jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleContainerDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(lblLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDetailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblContainerLatitude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLongitude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblContainerLongitude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContainerId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelContainerType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelDetailLayout.setVerticalGroup(
            jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleContainerDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblContainerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelContainerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLatitude)
                    .addComponent(lblLongitude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContainerLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContainerLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        //Tanquem el formulari
        this.dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        //Posem les variable a null per una nova comunicació amb el server
        serverMessageError = null;
        serverMessageOK = null;
        
        ////////////////////////////////////////////////////////////////////////////
        //Conectem amb el servidor per eliminar un contenidor
        ////////////////////////////////////////////////////////////////////////////
        
        ContainersManagement container = new ContainersManagement();
        serverResponse = container.containerDelete(Login.PUBLIC_URL_CONTAINER, Login.token, id);
        
        System.out.println("Resposta server al eliminar contanidor: " + serverResponse);
        
        //Mirem el tipus de missatge que retorna el servidor
        serverMessageOK = JsonUtils.findJsonValue(serverResponse, "OK");
        serverMessageError = JsonUtils.findJsonValue(serverResponse, "error");
        
        //Hi ha missatge d'error?
        if (serverMessageError != null) {
            
            //Mostrem un missatge
            JOptionPane.showMessageDialog(null, serverMessageError, "CityNet - Eliminar contenidor", JOptionPane.ERROR_MESSAGE);
            
            //Si l'error és de sessió finalitzada...
            if (serverResponse.equals("Not a valid token")) {
                
                //Tanquem l'aplicació
                System.exit(0);
                
            }
            
        }
        
        //Si s'ha eliminat
        if (serverMessageOK != null) {
            
            //Mostrem un missatge
            JOptionPane.showMessageDialog(null, serverMessageOK, "CityNet - Eliminar contenidor", JOptionPane.INFORMATION_MESSAGE);
            
            //Actualitzem la taula
            modelTable.removeRow(selectedRow);
            
            //Tanquem el formulari
            this.dispose();
            
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelContainerType;
    private javax.swing.JPanel jPanelDetail;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContainerId;
    private javax.swing.JLabel lblContainerLatitude;
    private javax.swing.JLabel lblContainerLongitude;
    private javax.swing.JLabel lblContainerType;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLatitude;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblLongitude;
    private javax.swing.JLabel lblTitleContainerDelete;
    private javax.swing.JLabel lblType;
    // End of variables declaration//GEN-END:variables
}
