package com.openfactorybeans.citynet.desktop.forms;

import com.openfactorybeans.citynet.desktop.management.ContainersManagement;
import com.openfactorybeans.citynet.desktop.model.Container;
import com.openfactorybeans.citynet.desktop.utils.ContainerMap;
import com.openfactorybeans.citynet.desktop.utils.JsonUtils;
import com.openfactorybeans.citynet.desktop.utils.TMContainer;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Formulari per modificar la localització d'un contenidor
 * 
 * @author Jose
 */
public class ContainerLocModify extends javax.swing.JInternalFrame {
    
    //Variables de la taula
    private Container container;
    private TMContainer modelTable;
    private int selectedRow;
    
    //Variable per la connexió amb el servidor
    private String serverResponse;
    private String serverMessageError;
    private String serverMessageOK;
    
    //Variables per definir el mapa
    private String zoom, mapType;

    /**
     * Creates new form ContainerLocModify
     * 
     * @param container Contenidor a eliminar
     * @param modelTable Model de la taula de contenidors
     * @param selectedRow Index de la fila seleccionada
     */
    public ContainerLocModify(Container container, TMContainer modelTable, int selectedRow) {
        initComponents();
        
        this.container = container;
        this.modelTable = modelTable;
        this.selectedRow = selectedRow;
        
        lblContainerId.setText(container.getId());
        lblContainerType.setText(container.getType());
        txtLatitude.setText(container.getLatitude().toString());
        txtLongitude.setText(container.getLongitude().toString());
        
        //Amaguem el panel dels modificadors del mapa. Només es veuran quan es cliqui el mapa
        jPanelMapButtons.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleContainerLocModify = new javax.swing.JLabel();
        jPanelDetail = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblContainerId = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelContainerType = new javax.swing.JPanel();
        lblType = new javax.swing.JLabel();
        lblContainerType = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblLocation = new javax.swing.JLabel();
        lblLatitude = new javax.swing.JLabel();
        txtLatitude = new javax.swing.JTextField();
        lblLongitude = new javax.swing.JLabel();
        txtLongitude = new javax.swing.JTextField();
        jPanelButtons = new javax.swing.JPanel();
        btnModify = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnMap = new javax.swing.JButton();
        jPanelMapButtons = new javax.swing.JPanel();
        chboxSatelite = new javax.swing.JCheckBox();
        btnZoomMore = new javax.swing.JButton();
        btbZoomLess = new javax.swing.JButton();
        jPanelMap = new javax.swing.JPanel();
        lblMap = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(913, 370));

        lblTitleContainerLocModify.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitleContainerLocModify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleContainerLocModify.setText("Modificar la localització del contenidor");
        lblTitleContainerLocModify.setPreferredSize(new java.awt.Dimension(0, 24));

        lblId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblId.setText("Identificador:");

        lblContainerId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContainerId.setForeground(new java.awt.Color(102, 0, 0));
        lblContainerId.setPreferredSize(new java.awt.Dimension(50, 19));

        lblType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblType.setText("Tipus de contenidor:");

        lblContainerType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContainerType.setForeground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanelContainerTypeLayout = new javax.swing.GroupLayout(jPanelContainerType);
        jPanelContainerType.setLayout(jPanelContainerTypeLayout);
        jPanelContainerTypeLayout.setHorizontalGroup(
            jPanelContainerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContainerType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContainerTypeLayout.setVerticalGroup(
            jPanelContainerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerTypeLayout.createSequentialGroup()
                .addGroup(jPanelContainerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(lblContainerType, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblLocation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLocation.setText("Ubicació");

        lblLatitude.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLatitude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLatitude.setText("Latitud");

        txtLatitude.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLatitude.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLatitude.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLatitudeFocusGained(evt);
            }
        });

        lblLongitude.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLongitude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLongitude.setText("Longitud");

        txtLongitude.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLongitude.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLongitude.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLongitudeFocusGained(evt);
            }
        });

        btnModify.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnModify.setText("Modificar");
        btnModify.setPreferredSize(new java.awt.Dimension(101, 35));
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setText("Cancel·lar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnMap.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMap.setText("Mapa");
        btnMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnMap)
                .addContainerGap())
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel)
                    .addComponent(btnMap))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chboxSatelite.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chboxSatelite.setText("Satèl·lit");
        chboxSatelite.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chboxSateliteStateChanged(evt);
            }
        });

        btnZoomMore.setText("+");
        btnZoomMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomMoreActionPerformed(evt);
            }
        });

        btbZoomLess.setText("-");
        btbZoomLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbZoomLessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMapButtonsLayout = new javax.swing.GroupLayout(jPanelMapButtons);
        jPanelMapButtons.setLayout(jPanelMapButtonsLayout);
        jPanelMapButtonsLayout.setHorizontalGroup(
            jPanelMapButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMapButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chboxSatelite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnZoomMore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btbZoomLess)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMapButtonsLayout.setVerticalGroup(
            jPanelMapButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMapButtonsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelMapButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chboxSatelite)
                    .addComponent(btnZoomMore)
                    .addComponent(btbZoomLess)))
        );

        javax.swing.GroupLayout jPanelDetailLayout = new javax.swing.GroupLayout(jPanelDetail);
        jPanelDetail.setLayout(jPanelDetailLayout);
        jPanelDetailLayout.setHorizontalGroup(
            jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(lblLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDetailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLongitude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDetailLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtLongitude)
                        .addContainerGap())))
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelContainerType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelDetailLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblContainerId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDetailLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelMapButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelDetailLayout.setVerticalGroup(
            jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblContainerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelContainerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLatitude)
                    .addComponent(lblLongitude))
                .addGap(7, 7, 7)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMapButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMapLayout = new javax.swing.GroupLayout(jPanelMap);
        jPanelMap.setLayout(jPanelMapLayout);
        jPanelMapLayout.setHorizontalGroup(
            jPanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMap, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanelMapLayout.setVerticalGroup(
            jPanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(lblTitleContainerLocModify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleContainerLocModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed

        //Posem les variables a null per una nova comunicació amb el server
        serverMessageError = null;
        serverMessageOK = null;
        
        //Obtenim el valor necessatir per passar al servidor
        String containerId = lblContainerId.getText();
        Double latitude = Double.parseDouble(txtLatitude.getText());
        Double longitude = Double.parseDouble(txtLongitude.getText());

        ////////////////////////////////////////////////////////////////////////////
        //Conectem amb el servidor per eliminar un contenidor
        ////////////////////////////////////////////////////////////////////////////

        ContainersManagement containerToLocModify = new ContainersManagement();
        serverResponse = containerToLocModify.containerLocationModification(Login.PUBLIC_URL_CONTAINER, Login.token, containerId, latitude, longitude);

        System.out.println("Resposta server al modificar la localització del contanidor: " + serverResponse);

        //Mirem el tipus de missatge que retorna el servidor
        serverMessageOK = JsonUtils.findJsonValue(serverResponse, "OK");
        serverMessageError = JsonUtils.findJsonValue(serverResponse, "error");

        //Hi ha missatge d'error?
        if (serverMessageError != null) {

            //Mostrem un missatge
            JOptionPane.showMessageDialog(null, serverMessageError, "CityNet - Modificar localització", JOptionPane.ERROR_MESSAGE);

            //Si l'error és de sessió finalitzada...
            if (serverResponse.equals("Not a valid token")) {

                //Tanquem l'aplicació
                System.exit(0);

            }

        }

        //Si s'ha modificat
        if (serverMessageOK != null) {

            //Mostrem un missatge
            JOptionPane.showMessageDialog(null, serverMessageOK, "CityNet - Modificar localització", JOptionPane.INFORMATION_MESSAGE);

            //Actualitzem la taula
            modelTable.locationModify(selectedRow, latitude, longitude);

            //Tanquem el formulari
            this.dispose();

        }

    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        //Tanquem el formulari
        this.dispose();

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapActionPerformed

        //Iniciem els valors per defecte del mapa
        zoom = "18";
        mapType = "roadmap";
        chboxSatelite.setSelected(false);
        
        //Passem els valors dels camps Latitud i Longitud
        Double latitude = Double.parseDouble(txtLatitude.getText());
        Double longitude = Double.parseDouble(txtLongitude.getText());
        container.setLatitude(latitude);
        container.setLongitude(longitude);
        
        //Instanciem el mapa
        ContainerMap containerMap = new ContainerMap(container, zoom, mapType);

        //Obtenim la imatge
        Image imageMap = containerMap.downloadMap();

        //Passem la imatge a l'etiqueta
        lblMap.setIcon(new ImageIcon(imageMap));
        
        //Mostrem el panel dels butons del mapa
        jPanelMapButtons.setVisible(true);

    }//GEN-LAST:event_btnMapActionPerformed

    private void txtLatitudeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLatitudeFocusGained
        
        txtLatitude.selectAll();
        
    }//GEN-LAST:event_txtLatitudeFocusGained

    private void txtLongitudeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLongitudeFocusGained
        
        txtLongitude.selectAll();
        
    }//GEN-LAST:event_txtLongitudeFocusGained

    private void btnZoomMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomMoreActionPerformed
        
        //Obtenim el zoom actual
        int zoomTemp = Integer.parseInt(zoom);
        
        //Incrementem en 1 el zoom i controlem que no passi del límit
        zoomTemp ++;
        if (zoomTemp >= 21) zoomTemp = 21;
        
        //Passem el resultat a un String
        zoom = String.valueOf(zoomTemp);
        
        //Instanciem el mapa
        ContainerMap containerMap = new ContainerMap(container, zoom, mapType);

        //Obtenim la imatge
        Image imageMap = containerMap.downloadMap();

        //Passem la imatge a l'etiqueta
        lblMap.setIcon(new ImageIcon(imageMap));
        
    }//GEN-LAST:event_btnZoomMoreActionPerformed

    private void btbZoomLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbZoomLessActionPerformed
        
        //Obtenim el zoom actual
        int zoomTemp = Integer.parseInt(zoom);
        
        //Decrementem en 1 el zoom i controlem que no passi del límit
        zoomTemp --;
        if (zoomTemp <= 16) zoomTemp = 16;
        
        //Passem el resultat a un String
        zoom = String.valueOf(zoomTemp);
        
        //Instanciem el mapa
        ContainerMap containerMap = new ContainerMap(container, zoom, mapType);

        //Obtenim la imatge
        Image imageMap = containerMap.downloadMap();

        //Passem la imatge a l'etiqueta
        lblMap.setIcon(new ImageIcon(imageMap));
        
    }//GEN-LAST:event_btbZoomLessActionPerformed

    private void chboxSateliteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chboxSateliteStateChanged
        
        //Obtenim el valor del checkbox
        boolean chbox = chboxSatelite.isSelected();
        
        //Verifiquem el valor
        if (chbox) {
            mapType = "satellite";
        } else {
            mapType = "roadmap";
        }
        
        //Instanciem el mapa
        ContainerMap containerMap = new ContainerMap(container, zoom, mapType);

        //Obtenim la imatge
        Image imageMap = containerMap.downloadMap();

        //Passem la imatge a l'etiqueta
        lblMap.setIcon(new ImageIcon(imageMap));
        
    }//GEN-LAST:event_chboxSateliteStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbZoomLess;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnMap;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnZoomMore;
    private javax.swing.JCheckBox chboxSatelite;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelContainerType;
    private javax.swing.JPanel jPanelDetail;
    private javax.swing.JPanel jPanelMap;
    private javax.swing.JPanel jPanelMapButtons;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContainerId;
    private javax.swing.JLabel lblContainerType;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLatitude;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblLongitude;
    private javax.swing.JLabel lblMap;
    private javax.swing.JLabel lblTitleContainerLocModify;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLongitude;
    // End of variables declaration//GEN-END:variables
}
