package com.openfactorybeans.citynet.desktop.forms;

import com.openfactorybeans.citynet.desktop.management.ContainersManagement;
import com.openfactorybeans.citynet.desktop.model.Container;
import com.openfactorybeans.citynet.desktop.utils.JsonUtils;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * Formulari per afegir un nou usuari
 * 
 * @author Jose
 */
public class ContainerAdd extends javax.swing.JInternalFrame {
    
    //Declaració de les variables del formulari
    private String containerId;
    private int typeId;
    private Double latitude, longitude;
    private Container container = new Container();
    
    //Declaració de la variable error
    private boolean noError;

    /**
     * Creates new form ContainerAdd
     */
    public ContainerAdd() {
        initComponents();
        
        //Posem l'estat inicial del formulari
        initialStateForm();
        
        //Afegim els items del combo
        cbxContainerType.addItem(Container.TYPES_TABLE[0]); //Paper i cartró
        cbxContainerType.addItem(Container.TYPES_TABLE[1]); //Vidre
        cbxContainerType.addItem(Container.TYPES_TABLE[2]); //Envasos lleugers
        cbxContainerType.addItem(Container.TYPES_TABLE[3]); //Matèria orgànica
        cbxContainerType.addItem(Container.TYPES_TABLE[4]); //Rebuig
    }
    
    /**
     * Estat inicial del formulari amb els camps sense dades i
     * el panel de missatges ocult
     */
    public void initialStateForm() {
        
        txtContainerId.setText("");
        cbxContainerType.setSelectedIndex(0);
        txtLatitude.setText("");
        txtLongitude.setText("");
        lblMessagesError.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainerID = new javax.swing.JPanel();
        lblContainerId = new javax.swing.JLabel();
        txtContainerId = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelContainerType = new javax.swing.JPanel();
        lblContainerType = new javax.swing.JLabel();
        cbxContainerType = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelContainerLocation = new javax.swing.JPanel();
        lblLocation = new javax.swing.JLabel();
        lblLatitude = new javax.swing.JLabel();
        txtLatitude = new javax.swing.JTextField();
        lblLongitude = new javax.swing.JLabel();
        txtLongitude = new javax.swing.JTextField();
        jPanelButtons = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblMessagesError = new javax.swing.JLabel();

        setTitle("Afegir contenidor");

        lblContainerId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContainerId.setText("Identificació:");

        txtContainerId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtContainerId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContainerId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContainerIdFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanelContainerIDLayout = new javax.swing.GroupLayout(jPanelContainerID);
        jPanelContainerID.setLayout(jPanelContainerIDLayout);
        jPanelContainerIDLayout.setHorizontalGroup(
            jPanelContainerIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerIDLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lblContainerId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContainerId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContainerIDLayout.setVerticalGroup(
            jPanelContainerIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContainerIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContainerId)
                    .addComponent(txtContainerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblContainerType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContainerType.setText("Tipus de contenidor:");

        cbxContainerType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbxContainerType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona tipus" }));

        javax.swing.GroupLayout jPanelContainerTypeLayout = new javax.swing.GroupLayout(jPanelContainerType);
        jPanelContainerType.setLayout(jPanelContainerTypeLayout);
        jPanelContainerTypeLayout.setHorizontalGroup(
            jPanelContainerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblContainerType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxContainerType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelContainerTypeLayout.setVerticalGroup(
            jPanelContainerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerTypeLayout.createSequentialGroup()
                .addGroup(jPanelContainerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContainerType)
                    .addComponent(cbxContainerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblLocation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLocation.setText("Ubicació");

        lblLatitude.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLatitude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLatitude.setText("Latitud");

        txtLatitude.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLatitude.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLatitude.setToolTipText("Del tius 0.0000");
        txtLatitude.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLatitudeFocusGained(evt);
            }
        });

        lblLongitude.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLongitude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLongitude.setText("Longitud");

        txtLongitude.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLongitude.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLongitude.setToolTipText("Del tius 0.0000");
        txtLongitude.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLongitudeFocusGained(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAdd.setText("Afegir");
        btnAdd.setPreferredSize(new java.awt.Dimension(101, 35));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnClear.setText("Netejar");
        btnClear.setPreferredSize(new java.awt.Dimension(101, 35));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setText("Cancel·lar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addGap(18, 18, 18))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelContainerLocationLayout = new javax.swing.GroupLayout(jPanelContainerLocation);
        jPanelContainerLocation.setLayout(jPanelContainerLocationLayout);
        jPanelContainerLocationLayout.setHorizontalGroup(
            jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLocationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelContainerLocationLayout.createSequentialGroup()
                        .addGroup(jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLatitude, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txtLatitude))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLongitude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addComponent(jPanelButtons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelContainerLocationLayout.setVerticalGroup(
            jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLocationLayout.createSequentialGroup()
                .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLatitude)
                    .addComponent(lblLongitude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblMessagesError.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMessagesError.setForeground(new java.awt.Color(102, 0, 0));
        lblMessagesError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessagesError.setPreferredSize(new java.awt.Dimension(0, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContainerType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelContainerLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanelContainerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(lblMessagesError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContainerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContainerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContainerLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessagesError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        //Posem l'estat inicial del formulari
        initialStateForm();
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        //Tanquem el formulari
        this.dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        //Variables de comunicació del servidor
        String serverResponse;
        String serverMessageError = null;
        String serverMessageOK = null;
        
        //Eliminem qualsevol tipus de missatges d'error
        lblMessagesError.setText("");
        
        //Posem les etiquete del color per defecte
        lblContainerId.setForeground(Color.BLACK);
        lblContainerType.setForeground(Color.BLACK);
        lblLatitude.setForeground(Color.BLACK);
        lblLongitude.setForeground(Color.BLACK);
        
        //Posem el sensor d'errors a true (no hi ha errors per defecte
        noError = true;
        
        //////////////////////////////////////////////////////////
        //Recollim els valors del formulari i verifiquem les dades
        //////////////////////////////////////////////////////////
        
        //Camp ID. El passem a majúscules
        containerId = txtContainerId.getText().toUpperCase();
        //Ha de ser de 6 caràcters
        if (containerId.length() != 6) {
            
            //Mostrem l'etiqueta del camp en un altre color
            lblContainerId.setForeground(Color.RED);
            
            noError = false;
            
        } else {
            
            //Passem l'atribut al container
            container.setId(containerId);
            
        }
        
        //Camp tipus
        typeId = cbxContainerType.getSelectedIndex();
        if (typeId == 0) {
            
            //Mostrem l'etiqueta del camp en un altre color
            lblContainerType.setForeground(Color.RED);
            
            noError = false;
            
        } else {
            
            //Passem l'atribut al container
            int typeID = cbxContainerType.getSelectedIndex();
            
            switch (typeID) {
                
                case 1:
                    container.setType(Container.TYPES_SERVER[typeID - 1]); //paper
                    break;
                    
                case 2:
                    container.setType(Container.TYPES_SERVER[typeID - 1]); //glass
                    break;
                    
                case 3:
                    container.setType(Container.TYPES_SERVER[typeID - 1]); //packaging
                    break;
                    
                case 4:
                    container.setType(Container.TYPES_SERVER[typeID - 1]); //organic
                    break;
                    
                case 5:
                    container.setType(Container.TYPES_SERVER[typeID - 1]); //trash
                    break;
                
            }
            
        }
        
        //Camp latitud
        try {
            
            latitude = Double.parseDouble(txtLongitude.getText());
            
            //Passem l'atribut al container
            container.setLatitude(latitude);
            
        } catch (NumberFormatException nfe) {
            
            //Mostrem l'etiqueta del camp en un altre color
            lblLongitude.setForeground(Color.RED);
            
            noError = false;
            
        }
     
        //Camp longitud
        try {
            
            longitude = Double.parseDouble(txtLatitude.getText());
            
            //Passem l'atribut al container
            container.setLongitude(longitude);
            
        } catch (NumberFormatException nfe) {
            
            //Mostrem l'etiqueta del camp en un altre color
            lblLatitude.setForeground(Color.RED);
            
            noError = false;
            
        }
        
        //Si no hi ha errors
        if (noError) {

            //Passar les dades al server
            System.out.println("ID contenidor: " + container.getId());
            System.out.println("Tipus de contenior: " + container.getType());
            System.out.println("Latitud: " + container.getLatitude());
            System.out.println("Longitud: " + container.getLongitude());
            
            ////////////////////////////////////////////////////////////////////////////
            //Conectem amb el servidor per afegir un container
            ////////////////////////////////////////////////////////////////////////////
            ContainersManagement containerToAdd = new ContainersManagement();
            serverResponse = containerToAdd.containerRegister(Login.PUBLIC_URL_CONTAINER, Login.token, container);
            
            //Mirem el tipus de missatge que retorna el servidor
            serverMessageOK = JsonUtils.findJsonValue(serverResponse, "OK");
            serverMessageError = JsonUtils.findJsonValue(serverResponse, "error");
            
            //Hi ha messatge OK?
            if (serverMessageOK != null) {
                
                //Mostrem un missatge
                JOptionPane.showMessageDialog(null, serverMessageOK, "CityNet - Afegir container", JOptionPane.INFORMATION_MESSAGE);
                //Tanquem el formulari
                this.dispose();
                
            }
            
            //Hi ha messatge d'error?
            if (serverMessageError != null) {
                
                //No registrat. Mostrem el messatge
                lblMessagesError.setText(serverMessageError);
                
            }
            
        } else {
            
            //Mostrem un missatge
            lblMessagesError.setText("Incorrect data");
            
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtContainerIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContainerIdFocusGained
        txtContainerId.setSelectionStart(0);
        txtContainerId.setSelectionEnd(txtContainerId.getText().length());
    }//GEN-LAST:event_txtContainerIdFocusGained

    private void txtLatitudeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLatitudeFocusGained
        txtLatitude.setSelectionStart(0);
        txtLatitude.setSelectionEnd(txtLatitude.getText().length());
    }//GEN-LAST:event_txtLatitudeFocusGained

    private void txtLongitudeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLongitudeFocusGained
        txtLongitude.setSelectionStart(0);
        txtLongitude.setSelectionEnd(txtLongitude.getText().length());
    }//GEN-LAST:event_txtLongitudeFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> cbxContainerType;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelContainerID;
    private javax.swing.JPanel jPanelContainerLocation;
    private javax.swing.JPanel jPanelContainerType;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContainerId;
    private javax.swing.JLabel lblContainerType;
    private javax.swing.JLabel lblLatitude;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblLongitude;
    private javax.swing.JLabel lblMessagesError;
    private javax.swing.JTextField txtContainerId;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLongitude;
    // End of variables declaration//GEN-END:variables
}
