/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openfactorybeans.citynet.desktop.forms;

import com.openfactorybeans.citynet.desktop.containers.AddContainer;
import com.openfactorybeans.citynet.desktop.containers.Container;
import com.openfactorybeans.citynet.desktop.utils.JsonUtils;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * Formulari per afegir un nou usuari
 * 
 * @author Jose
 */
public class ContainerAdd extends javax.swing.JInternalFrame {
    
    //Declaració de les variables del formulari
    private int typeId;
    private String type;
    private Double longitude, latitude;
    private Container container = new Container();
    
    //Declaració de la variable error
    private boolean noError;

    /**
     * Creates new form ContainerAdd
     */
    public ContainerAdd() {
        initComponents();
        
        //Posem l'estat inicial del formulari
        initialStateForm();
    }
    
    /**
     * Estat inicial del formulari amb els camps sense dades i
     * el panel de missatges ocult
     */
    public void initialStateForm() {
        
        cbxContainerType.setSelectedIndex(0);
        txtLatitude.setText("");
        txtLongitude.setText("");
        lblMessagesError.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainerType = new javax.swing.JPanel();
        lblContainerType = new javax.swing.JLabel();
        cbxContainerType = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelContainerLocation = new javax.swing.JPanel();
        lblLocation = new javax.swing.JLabel();
        lblLongitude = new javax.swing.JLabel();
        txtLongitude = new javax.swing.JTextField();
        lblLatitude = new javax.swing.JLabel();
        txtLatitude = new javax.swing.JTextField();
        jPanelButtons = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblMessagesError = new javax.swing.JLabel();

        setTitle("Afegir contenidor");

        lblContainerType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContainerType.setText("Tipus de contenidor:");

        cbxContainerType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbxContainerType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona tipus", "Paper i cartró (blau)", "Vidre (verd)", "Envasos lleugers (groc)", "Matèria orgànica (marró)", "Rebuig (gris)" }));

        javax.swing.GroupLayout jPanelContainerTypeLayout = new javax.swing.GroupLayout(jPanelContainerType);
        jPanelContainerType.setLayout(jPanelContainerTypeLayout);
        jPanelContainerTypeLayout.setHorizontalGroup(
            jPanelContainerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblContainerType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxContainerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContainerTypeLayout.setVerticalGroup(
            jPanelContainerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblContainerType)
                .addComponent(cbxContainerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblLocation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLocation.setText("Ubicació");

        lblLongitude.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLongitude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLongitude.setText("Longitud");

        txtLongitude.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLongitude.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLongitude.setToolTipText("Del tius 0.0000");

        lblLatitude.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLatitude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLatitude.setText("Latitud");

        txtLatitude.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLatitude.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLatitude.setToolTipText("Del tius 0.0000");

        btnAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAdd.setText("Afegir");
        btnAdd.setPreferredSize(new java.awt.Dimension(101, 35));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnClear.setText("Netejar");
        btnClear.setPreferredSize(new java.awt.Dimension(101, 35));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setText("Cancel·lar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addGap(18, 18, 18))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelContainerLocationLayout = new javax.swing.GroupLayout(jPanelContainerLocation);
        jPanelContainerLocation.setLayout(jPanelContainerLocationLayout);
        jPanelContainerLocationLayout.setHorizontalGroup(
            jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLocationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelContainerLocationLayout.createSequentialGroup()
                        .addGroup(jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtLongitude, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLongitude, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLatitude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLatitude))))
                .addContainerGap())
            .addComponent(jPanelButtons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelContainerLocationLayout.setVerticalGroup(
            jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLocationLayout.createSequentialGroup()
                .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLongitude)
                    .addComponent(lblLatitude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContainerLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblMessagesError.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMessagesError.setForeground(new java.awt.Color(102, 0, 0));
        lblMessagesError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessagesError.setPreferredSize(new java.awt.Dimension(0, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContainerType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelContainerLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessagesError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContainerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContainerLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessagesError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        //Posem l'estat inicial del formulari
        initialStateForm();
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        //Tanquem el formulari
        this.dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        //Variables de comunicació del servidor
        String serverResponse;
        String serverMessageError = null;
        String serverMessageOK = null;
        
        //Eliminem qualsevol tipus de missatges d'error
        lblMessagesError.setText("");
        
        //Posem les etiquete del color per defecte
        lblContainerType.setForeground(Color.BLACK);
        lblLongitude.setForeground(Color.BLACK);
        lblLatitude.setForeground(Color.BLACK);
        
        //Posem el sensor d'errors a true (no hi ha errors per defecte
        noError = true;
        
        //Recollim els valors del formulari i verifiquem les dades
        
        //Camp tipus
        typeId = cbxContainerType.getSelectedIndex();
        if (typeId == 0) {
            
            //Mostrem l'etiqueta del camp en un altre color
            lblContainerType.setForeground(Color.RED);
            
            noError = false;
            
        } else {
            
            //Passem l'atribut al container
            switch (cbxContainerType.getSelectedIndex()) {
                
                case 1:
                    container.setType(Container.PAPER);
                    break;
                    
                case 2:
                    container.setType(Container.GLASS);
                    break;
                    
                case 3:
                    container.setType(Container.PACKAGING);
                    break;
                    
                case 4:
                    container.setType(Container.ORGANIC);
                    break;
                    
                case 5:
                    container.setType(Container.TRASH);
                    break;
                
            }
            
        }
        
        //Camp longitud
        try {
            
            longitude = Double.parseDouble(txtLongitude.getText());
            
            //Passem l'atribut al container
            container.setLongitude(longitude);
            
        } catch (NumberFormatException nfe) {
            
            //Mostrem l'etiqueta del camp en un altre color
            lblLongitude.setForeground(Color.RED);
            
            //Mostrem un missatge
            lblMessagesError.setText("Incorrect data");
            
            noError = false;
            
        }
        
        //Camp latitud
        try {
            
            latitude = Double.parseDouble(txtLatitude.getText());
            
            //Passem l'atribut al container
            container.setLatitude(latitude);
            
        } catch (NumberFormatException nfe) {
            
            //Mostrem l'etiqueta del camp en un altre color
            lblLatitude.setForeground(Color.RED);
            
            //Mostrem un missatge
            lblMessagesError.setText("Incorrect data");
            
            noError = false;
            
        }
        
        //Si no hi ha errors
        if (noError) {
            container.setId("HI4K7U");
            //Passar les dades al server
            System.out.println("ID contenidor: " + container.getId());
            System.out.println("Tipus de contenior: " + container.getType());
            System.out.println("Longitud: " + container.getLongitude());
            System.out.println("Latitud: " + container.getLatitude());
            
            ////////////////////////////////////////////////////////////////////////////
            //Conectem amb el servidor per afegir un container
            ////////////////////////////////////////////////////////////////////////////
            AddContainer addContainer = new AddContainer();
            serverResponse = addContainer.containerRegister(Login.PUBLIC_URL_CONTAINERS, Login.token, container);
            
            //Mirem el tipus de missatge que retorna el servidor
            serverMessageOK = JsonUtils.findJsonValue(serverResponse, "OK");
            serverMessageError = JsonUtils.findJsonValue(serverResponse, "error");
            
            //Hi ha messatge OK?
            if (serverMessageOK != null) {
                
                //Mostrem un missatge
                JOptionPane.showMessageDialog(null, serverMessageOK, "CityNet - Afegir container", JOptionPane.INFORMATION_MESSAGE);
                //Tanquem el formulari
                this.dispose();
                
            }
            
            //Hi ha messatge d'error?
            if (serverMessageError != null) {
                
                //No registrat. Mostrem el messatge
                lblMessagesError.setText(serverMessageError);
                
            }
            
        }
        
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> cbxContainerType;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelContainerLocation;
    private javax.swing.JPanel jPanelContainerType;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblContainerType;
    private javax.swing.JLabel lblLatitude;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblLongitude;
    private javax.swing.JLabel lblMessagesError;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLongitude;
    // End of variables declaration//GEN-END:variables
}
