package com.openfactorybeans.citynet.desktop.forms;

import com.openfactorybeans.citynet.desktop.model.User;
import com.openfactorybeans.citynet.desktop.utils.FormsUtils;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jose
 */
public class DesktopMain extends javax.swing.JFrame {

    /**
     * Creates new form DesktopMain
     */
    public DesktopMain() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        //Verifique el rol de l'usuari que ha iniciat la sessió
        checkOptionsRol();
        
        //Posem l'usuari al title de la finestra
        this.setTitle("CityNet - " + Login.user);
        
    }
    
    /**
     * Habilita o desabilita les opcions del menú en funció del rol
     */
    public void checkOptionsRol() {
        
        if (Login.rol.equals(User.UL_USER)) {
            
            //User Level "user". Deshabilitem tot menys les seves dades
            jMenuUsers.setVisible(false);
            jMenuContainers.setVisible(false);
            
        } else if (Login.rol.equals(User.UL_EDITOR)) {
            
            //User Level "editor". Deshabilitem el menú d'usuaris
            jMenuUsers.setVisible(false);
            
        }
        
        //Si es admin ja están tots els menús activats
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsers = new javax.swing.JMenu();
        optionAddUser = new javax.swing.JMenuItem();
        separatorUsers = new javax.swing.JPopupMenu.Separator();
        optionListUsers = new javax.swing.JMenuItem();
        jMenuContainers = new javax.swing.JMenu();
        opctionAddContainer = new javax.swing.JMenuItem();
        separatorContainers = new javax.swing.JPopupMenu.Separator();
        optionListContainers = new javax.swing.JMenuItem();
        jMenuMyMenu = new javax.swing.JMenu();
        optionModifyUserProfile = new javax.swing.JMenuItem();
        optionChangePass = new javax.swing.JMenuItem();
        separatorProfile = new javax.swing.JPopupMenu.Separator();
        optionLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenuUsers.setText("Usuaris");

        optionAddUser.setText("Afegir usuari");
        optionAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionAddUserActionPerformed(evt);
            }
        });
        jMenuUsers.add(optionAddUser);
        jMenuUsers.add(separatorUsers);

        optionListUsers.setText("Llistar usuaris");
        optionListUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionListUsersActionPerformed(evt);
            }
        });
        jMenuUsers.add(optionListUsers);

        jMenuBar1.add(jMenuUsers);

        jMenuContainers.setText("Contenidors");

        opctionAddContainer.setText("Afegir contenidor");
        opctionAddContainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opctionAddContainerActionPerformed(evt);
            }
        });
        jMenuContainers.add(opctionAddContainer);
        jMenuContainers.add(separatorContainers);

        optionListContainers.setText("Llistar contenidors");
        optionListContainers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionListContainersActionPerformed(evt);
            }
        });
        jMenuContainers.add(optionListContainers);

        jMenuBar1.add(jMenuContainers);

        jMenuMyMenu.setText("Perfil usuari");

        optionModifyUserProfile.setText("Modificar dades");
        optionModifyUserProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionModifyUserProfileActionPerformed(evt);
            }
        });
        jMenuMyMenu.add(optionModifyUserProfile);

        optionChangePass.setText("Canviar contrasenya");
        optionChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionChangePassActionPerformed(evt);
            }
        });
        jMenuMyMenu.add(optionChangePass);
        jMenuMyMenu.add(separatorProfile);

        optionLogout.setText("Tancar sessió");
        optionLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionLogoutActionPerformed(evt);
            }
        });
        jMenuMyMenu.add(optionLogout);

        jMenuBar1.add(jMenuMyMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optionListUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionListUsersActionPerformed
        
        //Netejem qualsevol finestra oberta anteriorment en l'escrptori
        jDesktop.removeAll();
        jDesktop.repaint();
        
        //Instanciem el JFrame Llistat
        UsersList userList = new UsersList();        
        
        //Afegim el formulari de llistat a l'escrptori
        jDesktop.add(userList);
        
        //Maximitzem el JInternalFrame
        try {
            userList.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DesktopMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //El fem visible
        userList.setVisible(true);
        
    }//GEN-LAST:event_optionListUsersActionPerformed

    private void optionLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionLogoutActionPerformed
        
        //Anulem les dades de sessió
        Login.token = null;
        Login.rol = null;
        
        //Amaguem l'escriptori i mostrem el login
        Login login = new Login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_optionLogoutActionPerformed

    private void optionAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionAddUserActionPerformed
        
        //Netejem qualsevol finestra oberta anteriorment en l'escrptori
        jDesktop.removeAll();
        jDesktop.repaint();
        
        //Instanciem el JFrame Afegir
        UserAdd userAdd = new UserAdd();
        
        //Afegim el formulari d'afegir a l'escriptori
        jDesktop.add(userAdd);
        
        //Centrem la finestra
        FormsUtils.centerDesktop(jDesktop, userAdd);
        
        //El fem visible
        userAdd.setVisible(true);
        
    }//GEN-LAST:event_optionAddUserActionPerformed

    private void optionChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionChangePassActionPerformed
        
        //Netejem qualsevol finestra oberta anteriorment en l'escrptori
        jDesktop.removeAll();
        jDesktop.repaint();
        
        //Instanciem el JFrame CanviarContrasenya
        UserChangePassword userChangePass = new UserChangePassword();
        
        //Afegim el formulari de canviar la contrasenya a l'escriptori
        jDesktop.add(userChangePass);
        
        //Centrem la finestra
        FormsUtils.centerDesktop(jDesktop, userChangePass);
        
        //El fem visible
        userChangePass.setVisible(true);
        
    }//GEN-LAST:event_optionChangePassActionPerformed

    private void optionModifyUserProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionModifyUserProfileActionPerformed
        
        //Netejem qualsevol finestra oberta anteriorment en l'escrptori
        jDesktop.removeAll();
        jDesktop.repaint();
        
        //Instanciem el JFrame per modificar les dades de perfil d'usuari
        UserUpdateProfile userUpdateProfile = new UserUpdateProfile();
        
        //Afegim el formulari a l'escriptori
        jDesktop.add(userUpdateProfile);
        
        //Centrem la finestra
        FormsUtils.centerDesktop(jDesktop, userUpdateProfile);
        
        //El fem visible
        userUpdateProfile.setVisible(true);
        
    }//GEN-LAST:event_optionModifyUserProfileActionPerformed

    private void opctionAddContainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opctionAddContainerActionPerformed
        
        //Netejem qualsevol finestra oberta anteriorment en l'escrptori
        jDesktop.removeAll();
        jDesktop.repaint();
        
        //Instanciem el JFrame per modificar les dades de perfil d'usuari
        ContainerAdd containerAdd = new ContainerAdd();
        
        //Afegirm el formulari a l'escriptori
        jDesktop.add(containerAdd);
        
        //Centrem la finestra
        FormsUtils.centerDesktop(jDesktop, containerAdd);
        
        //El fem visible
        containerAdd.setVisible(true);
        
    }//GEN-LAST:event_opctionAddContainerActionPerformed

    private void optionListContainersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionListContainersActionPerformed
        
        //Netejem qualsevol finestra oberta anteriorment en l'escrptori
        jDesktop.removeAll();
        jDesktop.repaint();
        
        //Instanciem el JFrame Llistat
        ContainersList containerList = new ContainersList();
        
        //Afegim el formulari de llistat a l'escrptori
        jDesktop.add(containerList);
        
        //Maximitzem el JInternalFrame
        try {
            containerList.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DesktopMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //El fem visible
        containerList.setVisible(true);
        
    }//GEN-LAST:event_optionListContainersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesktopMain().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuContainers;
    private javax.swing.JMenu jMenuMyMenu;
    private javax.swing.JMenu jMenuUsers;
    private javax.swing.JMenuItem opctionAddContainer;
    private javax.swing.JMenuItem optionAddUser;
    private javax.swing.JMenuItem optionChangePass;
    private javax.swing.JMenuItem optionListContainers;
    private javax.swing.JMenuItem optionListUsers;
    private javax.swing.JMenuItem optionLogout;
    private javax.swing.JMenuItem optionModifyUserProfile;
    private javax.swing.JPopupMenu.Separator separatorContainers;
    private javax.swing.JPopupMenu.Separator separatorProfile;
    private javax.swing.JPopupMenu.Separator separatorUsers;
    // End of variables declaration//GEN-END:variables
}
