/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openfactorybeans.citynet.desktop.forms;

import com.openfactorybeans.citynet.desktop.management.IncidentsManagement;
import com.openfactorybeans.citynet.desktop.model.Incident;
import com.openfactorybeans.citynet.desktop.utils.JsonUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class IncidentDetail extends javax.swing.JInternalFrame {
    
    //Variables de tipus de incidència
    private final String BROKEN = "broken";
    private final String FULL = "full";
    private final String BROKEN_TXT = "Trencat";
    private final String FULL_TXT = "Ple";
    
    //Variables per la connexxió amb el servidor
    private String serverResponse;
    private String serverMessageOK;
    private String serverMessageError;
    
    //Variables per la incidència
    private IncidentsManagement incidentManagement;
    private Incident incident;

    /**
     * Creates new form IncidentDetail
     */
    public IncidentDetail(String containerID) {
        initComponents();
        
        ////////////////////////////////////////////////////////////////////////////
        //Conectem amb el servidor per obtenidr les dades de la incidència
        ////////////////////////////////////////////////////////////////////////////
        incidentManagement = new IncidentsManagement();
        serverResponse = incidentManagement.askIncident(Login.PUBLIC_URL_CONTAINER, Login.token, containerID);

        //Mirem el tipus de missatge que retorna el servidor
        serverMessageOK = JsonUtils.findJsonValue(serverResponse, "OK");
        serverMessageError = JsonUtils.findJsonValue(serverResponse, "error");

        //Hi ha missatge d'error?
        if (serverMessageError != null) {

            //Mostrem un missatge
            JOptionPane.showMessageDialog(null, serverMessageError, "CityNet - Gestió de incidències", JOptionPane.ERROR_MESSAGE);

            //Si l'error és de sessió finalitzada...
            if (serverMessageError.equals("Not a valid token")) {

                //Tanquem l'aplicació
                System.exit(0);

            }

        } else {

            //Passem el Json a un Incident
            incident = new Incident();
            incident = JsonUtils.parseJsonIncident(serverResponse);

            //Passem la incidència al formulari
            lblTxtIncidentId.setText(String.valueOf(incident.getId()));
            String[] dateOnly =incident.getDate().split(" "); //Separem la data i l'hora
            lblTxtDateOpen.setText(dateOnly[0]); //Agafem no més la data
            lblTxtContainerId.setText(incident.getContainer());
            if (incident.getType().equals(BROKEN)) lblTxtIncidentType.setText(BROKEN_TXT);
            if (incident.getType().equals(FULL)) lblTxtIncidentType.setText(FULL_TXT);
            lblTxtUser.setText(incident.getUserEmail());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDetailIncident = new javax.swing.JPanel();
        lblIncidentId = new javax.swing.JLabel();
        lblTxtIncidentId = new javax.swing.JLabel();
        lblDateOpen = new javax.swing.JLabel();
        lblTxtDateOpen = new javax.swing.JLabel();
        lblContainerId = new javax.swing.JLabel();
        lblTxtContainerId = new javax.swing.JLabel();
        lblIncidentType = new javax.swing.JLabel();
        lblTxtIncidentType = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblTxtUser = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        lblIncidentId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblIncidentId.setText("Incidència n°:");

        lblTxtIncidentId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblDateOpen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblDateOpen.setText("Data obertura:");

        lblTxtDateOpen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblContainerId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblContainerId.setText("Contenidor:");

        lblTxtContainerId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblIncidentType.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblIncidentType.setText("Tipus:");

        lblTxtIncidentType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblUser.setText("Usuari:");

        lblTxtUser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanelDetailIncidentLayout = new javax.swing.GroupLayout(jPanelDetailIncident);
        jPanelDetailIncident.setLayout(jPanelDetailIncidentLayout);
        jPanelDetailIncidentLayout.setHorizontalGroup(
            jPanelDetailIncidentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailIncidentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetailIncidentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDetailIncidentLayout.createSequentialGroup()
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTxtUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDetailIncidentLayout.createSequentialGroup()
                        .addComponent(lblIncidentId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTxtIncidentId, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIncidentType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTxtIncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDateOpen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTxtDateOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDetailIncidentLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lblContainerId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTxtContainerId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDetailIncidentLayout.setVerticalGroup(
            jPanelDetailIncidentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailIncidentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDetailIncidentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContainerId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTxtContainerId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailIncidentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetailIncidentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDetailIncidentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIncidentId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTxtIncidentId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDetailIncidentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIncidentType)
                            .addComponent(lblTxtIncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDetailIncidentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDateOpen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTxtDateOpen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailIncidentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Detall de la incidència");

        btnOK.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnOK.setText("Acceptar");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDetailIncident, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(btnOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jPanelDetailIncident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        
        //Tanquem el formulari
        this.dispose();
        
    }//GEN-LAST:event_btnOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JPanel jPanelDetailIncident;
    private javax.swing.JLabel lblContainerId;
    private javax.swing.JLabel lblDateOpen;
    private javax.swing.JLabel lblIncidentId;
    private javax.swing.JLabel lblIncidentType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTxtContainerId;
    private javax.swing.JLabel lblTxtDateOpen;
    private javax.swing.JLabel lblTxtIncidentId;
    private javax.swing.JLabel lblTxtIncidentType;
    private javax.swing.JLabel lblTxtUser;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
