package com.openfactorybeans.citynet.desktop.forms;

import com.openfactorybeans.citynet.desktop.management.UsersManagement;
import com.openfactorybeans.citynet.desktop.model.User;
import com.openfactorybeans.citynet.desktop.utils.JsonUtils;
import javax.swing.JOptionPane;

/**
 * Codificació per actualizar les dades del perfil d'usuari
 * 
 * @author Jose
 */
public class UserUpdateProfile extends javax.swing.JInternalFrame {

    //Declaració de variables
    private String serverResponse;
    private String serverMessageOK;
    private String serverMessageError;
    private User user;
    
    /**
     * Creates new form UserUpdateProfile
     */
    public UserUpdateProfile() {
        initComponents();
        
        //Posem les variables de null per una nova comunicació amb el server
        serverMessageOK = null;
        serverMessageError = null;

        ////////////////////////////////////////////////////////////////////////////
        //Conectem amb el servidor per obtenir les dades de perfil.
        ////////////////////////////////////////////////////////////////////////////
        UsersManagement userToAskProfile = new UsersManagement();
        serverResponse = userToAskProfile.askUserProfile(Login.PUBLIC_URL_USER, Login.token);
        
        //Mirem el tipus de missatge que retorna el servidor
        serverMessageOK = JsonUtils.findJsonValue(serverResponse, "OK");
        serverMessageError = JsonUtils.findJsonValue(serverResponse, "error");
        
        //Hi ha missatge d'error?
        if (serverMessageError != null) {
            
            //Mostrem un missatge
            JOptionPane.showMessageDialog(null, serverMessageError, "CityNet - Modificar perfil", JOptionPane.ERROR_MESSAGE);
            
            //Si l'error és de sessió finalitzada...
            if (serverMessageError.equals("Not a valid token")) {
                
                //Tanquem l'aplicació
                System.exit(0);
                
            }
        
        } else {
            
            //Passem el Json a un User 
            user = new User();
            user = JsonUtils.parseJsonUser(serverResponse);

            //Omplim el formulari amb les dades actuals del perfil d'usuari
            txtName.setText(user.getName());
            txtSurname.setText(user.getSurname());
            txtAddress.setText(user.getAddress());
            txtPostalCode.setText(user.getPostcode());
            txtCity.setText(user.getCity());
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUserProfile = new javax.swing.JPanel();
        lblTitleUserProfile = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        lblSurname = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblPostalCode = new javax.swing.JLabel();
        txtPostalCode = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jPanelButtons = new javax.swing.JPanel();
        btnModifyProfile = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        lblTitleUserProfile.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitleUserProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleUserProfile.setText("Perfil d'usuari");

        lblName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblName.setText("Nom:");

        txtName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtName.setPreferredSize(new java.awt.Dimension(85, 27));
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
        });

        txtSurname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblSurname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSurname.setText("Cognoms:");

        lblAddress.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAddress.setText("Adreça:");

        txtAddress.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblPostalCode.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPostalCode.setText("CP:");

        txtPostalCode.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblCity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCity.setText("Població:");

        txtCity.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelUserProfileLayout = new javax.swing.GroupLayout(jPanelUserProfile);
        jPanelUserProfile.setLayout(jPanelUserProfileLayout);
        jPanelUserProfileLayout.setHorizontalGroup(
            jPanelUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleUserProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelUserProfileLayout.createSequentialGroup()
                        .addGroup(jPanelUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSurname)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUserProfileLayout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtSurname)))
                    .addGroup(jPanelUserProfileLayout.createSequentialGroup()
                        .addComponent(lblAddress)
                        .addGap(23, 23, 23)
                        .addComponent(txtAddress))
                    .addGroup(jPanelUserProfileLayout.createSequentialGroup()
                        .addComponent(lblPostalCode)
                        .addGap(53, 53, 53)
                        .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCity)))
                .addContainerGap())
        );
        jPanelUserProfileLayout.setVerticalGroup(
            jPanelUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserProfileLayout.createSequentialGroup()
                .addComponent(lblTitleUserProfile)
                .addGap(18, 18, 18)
                .addGroup(jPanelUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostalCode)
                    .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        btnModifyProfile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnModifyProfile.setText("Modificar");
        btnModifyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyProfileActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setText("Cancel·lar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(btnModifyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnCancel)
                .addGap(154, 154, 154))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifyProfile)
                    .addComponent(btnCancel)))
        );

        lblMessage.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(102, 0, 0));
        lblMessage.setPreferredSize(new java.awt.Dimension(0, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUserProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyProfileActionPerformed

        //Recollim les dades del formulari i les passem a l'instància user

        user.setName(txtName.getText());
        user.setSurname(txtSurname.getText());
        user.setAddress(txtAddress.getText());
        user.setPostcode(txtPostalCode.getText());
        user.setCity(txtCity.getText());
        
        //Posem les variables de null per una nova comunicació amb el server
        serverMessageOK = null;
        serverMessageError = null;

        ////////////////////////////////////////////////////////////////////////////
        //Conectem amb el servidor per obtenir les dades de perfil.
        ////////////////////////////////////////////////////////////////////////////
        UsersManagement userToUpdatePrfile = new UsersManagement();
        serverResponse = userToUpdatePrfile.updateUserProfile(Login.PUBLIC_URL_USER, Login.token, user);
        
        //Mirem el tipus de missatge que retorna el servidor
        serverMessageOK = JsonUtils.findJsonValue(serverResponse, "OK");
        serverMessageError = JsonUtils.findJsonValue(serverResponse, "error");
        
        //Hi ha missatge d'error?
        if (serverMessageError != null) {
            
            //Mostrem un missatge
            JOptionPane.showMessageDialog(null, serverMessageError, "CityNet - Modificar perfil", JOptionPane.ERROR_MESSAGE);
            
            //Si l'error és de sessió finalitzada...
            if (serverMessageError.equals("Not a valid token")) {
                
                //Tanquem l'aplicació
                System.exit(0);
                
            }
        
        } else {
            
            //Mostrem un missatge
            JOptionPane.showMessageDialog(null, serverMessageOK, "CityNet - Modificar perfil", JOptionPane.INFORMATION_MESSAGE);
            //Tanquem el formulari
            this.dispose();
            
        }
        
    }//GEN-LAST:event_btnModifyProfileActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        //Tanquem el formulari
        this.dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        txtName.setSelectionStart(0);
        txtName.setSelectionEnd(txtName.getText().length());
    }//GEN-LAST:event_txtNameFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnModifyProfile;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelUserProfile;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPostalCode;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTitleUserProfile;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPostalCode;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
