/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openfactorybeans.citynet.desktop.forms;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
import com.google.gson.reflect.TypeToken;
import com.openfactorybeans.citynet.desktop.users.ListAllUsers;
import com.openfactorybeans.citynet.desktop.users.TMUser;
import com.openfactorybeans.citynet.desktop.users.User;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Jose
 */
public class UsersList extends javax.swing.JInternalFrame {
    
    //Per fer proves
    private ListAllUsers lau;
    private List<User> users;
    private TMUser model;
    
    //URL
    private static final String PUBLIC_URL = "http://ec2-35-180-7-53.eu-west-3.compute.amazonaws.com:8080/citynet/UserManager";
    
    //Variable eque informa de la pàgina solicitada al servidor
    private int screen = 0;

    /**
     * Creates new form UsersList
     */
    public UsersList() {
        initComponents();
        
        ////////////////////////////////////////////////////////////////////////////
        //Conectem amb el servidor per obtenir els usuaris
        ////////////////////////////////////////////////////////////////////////////
        ListAllUsers lau = new ListAllUsers();
        
        String listJSon = lau.listAllUsers(screen, PUBLIC_URL);
        System.out.println("LLISTAT REBUT\n" + listJSon);
        listJSon = "[{\"email\":\"a3@a3.com\",\"name\":\"a3\",\"surname\":\"a3\",\"address\":\"a3\",\"postcode\":\"08150\",\"city\":\"a3\",\"userLevel\":\"user\"},{\"email\":\"a4@a4.com\",\"name\":\"a\",\"surname\":\"a4\",\"address\":\"a4\",\"postcode\":\"08150\",\"city\":\"a4\",\"userLevel\":\"user\"},{\"email\":\"a5\",\"name\":\"a5\",\"surname\":\"a5\",\"address\":\"a5\",\"postcode\":\"08150\",\"city\":\"a5\",\"userLevel\":\"user\"},{\"email\":\"a6a6@a6.com\",\"name\":\"a6\",\"surname\":\"a6\",\"address\":\"a6\",\"postcode\":\"08150\",\"city\":\"a6\",\"userLevel\":\"user\"},{\"email\":\"a7\",\"name\":\"a7\",\"surname\":\"a7\",\"address\":\"a7\",\"postcode\":\"08150\",\"city\":\"a7\",\"userLevel\":\"user\"},{\"email\":\"aaa2@a.com\",\"name\":\"sergi2\",\"surname\":\"garrido2\",\"address\":\"joanmiro\",\"postcode\":\"08150\",\"city\":\"Parets\",\"userLevel\":\"user\"},{\"email\":\"aaaa@a.com\",\"name\":\"sergi\",\"surname\":\"garrido\",\"address\":\"Johnmiro\",\"postcode\":\"08150\",\"city\":\"parets\",\"userLevel\":\"user\"},{\"email\":\"abel@usuari.com\",\"name\":\"Abel\",\"surname\":\"Usuari\",\"address\":\"Carrer\",\"postcode\":\"08581\",\"city\":\"Barcelona\",\"userLevel\":\"user\"},{\"email\":\"adelamiret@yo.com\",\"name\":\"Adela\",\"surname\":\"Miret\",\"address\":\"Av. del Caminet, s/n\",\"postcode\":\"08541\",\"city\":\"En alguna població\",\"userLevel\":\"user\"},{\"email\":\"alberto@usuari.com\",\"name\":\"Alta\",\"surname\":\"Usuari\",\"address\":\"Carrer de l'usuari 9\",\"postcode\":\"08581\",\"city\":\"Mataró\",\"userLevel\":\"user\"}]";
        //Passem de jSon a ArrayLisy
        Gson gson = new Gson();
        users = new ArrayList<>();
        
        //users = gson.fromJson(listJSon, new TypeToken<List<User>>(){}.getType());
        
        User[] user = gson.fromJson(listJSon, User[].class);
        
        for (User u : user) {
            
            users.add(u);
            
        }

        //ompleArray();
        fillTable();
        
    }
    

    /**
     * Mètode per fer proves... ESBORRAR
     */
    public void ompleArray() {
        
        users = new ArrayList<>();
        
        User user1 = new User("uno@uno.com", "1111", "Olga", "Altes", "C/ Rasade, 1", "11111", "Figueres");
        users.add(user1);
        
        User user2 = new User("dos@dos.com", "2222", "Rene", "Bouduou", "Concorde, 2", "22222", "París");
        users.add(user2);
        
    }
    
    /**
     * Omple la taula per mostrar els usuaris
     */
    public void fillTable() {
        
        model = new TMUser(users);

        jTableUsers.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jPanelButtons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);

        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Cognoms", "Adreça", "CP", "Població", "Email", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableUsers);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Primer");
        jButton1.setMaximumSize(new java.awt.Dimension(90, 35));
        jButton1.setMinimumSize(new java.awt.Dimension(90, 35));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 35));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Anterior");
        jButton2.setMaximumSize(new java.awt.Dimension(90, 35));
        jButton2.setMinimumSize(new java.awt.Dimension(90, 35));
        jButton2.setPreferredSize(new java.awt.Dimension(90, 35));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setText("Següent");
        jButton3.setMaximumSize(new java.awt.Dimension(90, 35));
        jButton3.setMinimumSize(new java.awt.Dimension(90, 35));
        jButton3.setPreferredSize(new java.awt.Dimension(90, 35));

        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setText("Últim");
        jButton4.setMaximumSize(new java.awt.Dimension(90, 35));
        jButton4.setMinimumSize(new java.awt.Dimension(90, 35));
        jButton4.setPreferredSize(new java.awt.Dimension(90, 35));

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsers;
    // End of variables declaration//GEN-END:variables
}
