package com.openfactorybeans.citynet.desktop.forms;

import com.openfactorybeans.citynet.desktop.users.ChangePassword;
import com.openfactorybeans.citynet.desktop.utils.JsonUtils;
import javax.swing.JOptionPane;

/**
 * Formulari per canviar la contrasenya
 * 
 * @author Jose
 */
public class UserChangePassword extends javax.swing.JInternalFrame {
    
    //Declaració de variables
    private String oldPass, newPass1, newPass2;
    private char[] oldP, newP1, newP2;
    private String serverResponse;
    private String serverMessageOK;
    private String serverMessageError;
    
    

    /**
     * Creates new form UserChangePassword
     */
    public UserChangePassword() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDetail = new javax.swing.JPanel();
        lblTitlePersonalInfo = new javax.swing.JLabel();
        lblOldPass = new javax.swing.JLabel();
        jPassOldPass = new javax.swing.JPasswordField();
        lblNewPass1 = new javax.swing.JLabel();
        jPassNewPass1 = new javax.swing.JPasswordField();
        lblNewPass2 = new javax.swing.JLabel();
        jPassNewPass2 = new javax.swing.JPasswordField();
        jPanelButtons = new javax.swing.JPanel();
        btnChangePass = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        lblTitlePersonalInfo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitlePersonalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePersonalInfo.setText("Canviar contrasenya");
        lblTitlePersonalInfo.setPreferredSize(new java.awt.Dimension(0, 24));

        lblOldPass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblOldPass.setText("Contrasenya antiga:");

        jPassOldPass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblNewPass1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNewPass1.setText("Contrasenya nova:");

        jPassNewPass1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblNewPass2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNewPass2.setText("Repetir contrasenya nova:");

        jPassNewPass2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelDetailLayout = new javax.swing.GroupLayout(jPanelDetail);
        jPanelDetail.setLayout(jPanelDetailLayout);
        jPanelDetailLayout.setHorizontalGroup(
            jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOldPass)
                    .addComponent(lblNewPass1)
                    .addComponent(lblNewPass2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPassOldPass)
                    .addComponent(jPassNewPass1)
                    .addComponent(jPassNewPass2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblTitlePersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelDetailLayout.setVerticalGroup(
            jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addComponent(lblTitlePersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOldPass)
                    .addComponent(jPassOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPass1)
                    .addComponent(jPassNewPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPass2)
                    .addComponent(jPassNewPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnChangePass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnChangePass.setText("Canviar");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setText("Cancel·lar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(btnCancel)
                .addGap(154, 154, 154))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePass)
                    .addComponent(btnCancel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelButtons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed

        //Posem les variables de null per una nova comunicació amb el server
        serverMessageError = null;
        serverMessageOK = null;
        
        //Obtenim els valor de la contrasenya antiga
        oldP = jPassOldPass.getPassword();
        oldPass = new String(oldP); //Passem el password a String
        
        //Obtenim els valor de la contrasenya nova
        newP1 = jPassNewPass1.getPassword();
        newPass1 = new String(newP1); //Passem el password a String
        
        //Obtenim els valor de la contrasenya nova repetida
        newP2 = jPassNewPass2.getPassword();
        newPass2 = new String(newP2); //Passem el password a String
        
        ////////////////////////////////////////////////////////////////////////////
        //Conectem amb el servidor per canviar la contrasenya d'un usuari
        ////////////////////////////////////////////////////////////////////////////
        ChangePassword changePassUser = new ChangePassword();
        serverResponse = changePassUser.changePassword(Login.PUBLIC_URL_USERS, Login.token, oldPass, newPass1);
        
        //Mirem el tipus de missatge que retorna el servidor
        serverMessageOK = JsonUtils.findJsonValue(serverResponse, "OK");
        serverMessageError = JsonUtils.findJsonValue(serverResponse, "error");
        
        //Hi ha messatge d'error?
        if (serverMessageError != null) {
            
            //Mostrem un missatge
            JOptionPane.showMessageDialog(null, serverMessageError, "CityNet - Canviar contrasenya", JOptionPane.ERROR_MESSAGE);
            
            //Si l'error és de sessió finalitzada...
            if (serverMessageError.equals("Not a valid token")) {
                
                //Tanquem l'aplicació
                System.exit(0);
                
            }
            
        }
        
        //Si s'ha canviat...
        if (serverMessageOK != null) {
            
            //Mostrem un missatge
            JOptionPane.showMessageDialog(null, serverMessageOK, "CityNet - Canviar contrasenya", JOptionPane.INFORMATION_MESSAGE);
            //Tanquem el formulari
            this.dispose();
            
        }
        

    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        //Tanquem el formulari
        this.dispose();

    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelDetail;
    private javax.swing.JPasswordField jPassNewPass1;
    private javax.swing.JPasswordField jPassNewPass2;
    private javax.swing.JPasswordField jPassOldPass;
    private javax.swing.JLabel lblNewPass1;
    private javax.swing.JLabel lblNewPass2;
    private javax.swing.JLabel lblOldPass;
    private javax.swing.JLabel lblTitlePersonalInfo;
    // End of variables declaration//GEN-END:variables
}
