package com.openfactorybeans.citynet.desktop.forms;

import com.openfactorybeans.citynet.desktop.users.DeleteUser;
import com.openfactorybeans.citynet.desktop.utils.JsonUtils;
import javax.swing.JOptionPane;

/**
 * Formulario per eliminar un usuari
 * 
 * @author Jose
 */
public class UserDelete extends javax.swing.JInternalFrame {
    
    //Declaració de les variables
    private String email;
    private String serverResponse;
    private String serverMessageError;
    private String serverMessageOK;

    /**
     * Creates new form UserDelete
     * @param email
     * @param name
     * @param surname
     * @param address
     * @param postalCode
     * @param city 
     */
    public UserDelete(String email, String name, String surname, String address, String postalCode, String city) {
        initComponents();
        
        btnCancel.requestFocus();
        
        this.email = email;

        //Passem el valor de la fila al formulari
        lblUserName.setText(name);
        lblUserSurname.setText(surname);
        lblUserAddress.setText(address);
        lblUserPostalCode.setText(postalCode);
        lblUserCity.setText(city);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDetail = new javax.swing.JPanel();
        lblTitlePersonalInfo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblUserSurname = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblUserAddress = new javax.swing.JLabel();
        lblPostCode = new javax.swing.JLabel();
        lblUserPostalCode = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblUserCity = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setClosable(true);

        lblTitlePersonalInfo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitlePersonalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePersonalInfo.setText("Eliminar usuari");
        lblTitlePersonalInfo.setPreferredSize(new java.awt.Dimension(0, 24));

        lblName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblName.setText("Nom:");

        lblUserName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(102, 0, 0));
        lblUserName.setPreferredSize(new java.awt.Dimension(0, 19));

        lblSurname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSurname.setText("Cognoms:");

        lblUserSurname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUserSurname.setForeground(new java.awt.Color(102, 0, 0));
        lblUserSurname.setPreferredSize(new java.awt.Dimension(0, 19));

        lblAddress.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAddress.setText("Adreça:");

        lblUserAddress.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUserAddress.setForeground(new java.awt.Color(102, 0, 0));
        lblUserAddress.setPreferredSize(new java.awt.Dimension(0, 19));

        lblPostCode.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPostCode.setText("Codi Postal:");

        lblUserPostalCode.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUserPostalCode.setForeground(new java.awt.Color(102, 0, 0));
        lblUserPostalCode.setPreferredSize(new java.awt.Dimension(70, 19));

        lblCity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCity.setText("Població:");

        lblUserCity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUserCity.setForeground(new java.awt.Color(102, 0, 0));
        lblUserCity.setPreferredSize(new java.awt.Dimension(0, 19));

        javax.swing.GroupLayout jPanelDetailLayout = new javax.swing.GroupLayout(jPanelDetail);
        jPanelDetail.setLayout(jPanelDetailLayout);
        jPanelDetailLayout.setHorizontalGroup(
            jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSurname)
                    .addComponent(lblName)
                    .addComponent(lblAddress)
                    .addComponent(lblPostCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblUserSurname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUserAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDetailLayout.createSequentialGroup()
                            .addComponent(lblUserPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                            .addComponent(lblCity)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblUserCity, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblTitlePersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelDetailLayout.setVerticalGroup(
            jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addComponent(lblTitlePersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname)
                    .addComponent(lblUserSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(lblUserAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPostCode)
                        .addComponent(lblCity)
                        .addComponent(lblUserCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setText("Cancel·lar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(btnCancel)
                .addGap(130, 130, 130))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        //Tanquem el formulari
        this.dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        //Posem les variables de null per una nova comunicació amb el server
        serverMessageError = null;
        serverMessageOK = null;
        
        ////////////////////////////////////////////////////////////////////////////
        //Conectem amb el servidor per eliminar un usuari
        ////////////////////////////////////////////////////////////////////////////
        DeleteUser deleteUser = new DeleteUser();
        serverResponse = deleteUser.userDelete(Login.PUBLIC_URL_USERS, Login.token, email);
        
        System.out.println("Resposta server al eliminar usuari: " + serverResponse);
        
        //Mirem el tipus de missatge que retorna el servidor
        serverMessageOK = JsonUtils.findJsonValue(serverResponse, "OK");
        serverMessageError = JsonUtils.findJsonValue(serverResponse, "error");
        
        //Hi ha messatge d'error?
        if (serverMessageError != null) {
            
            //Mostrem un missatge
            JOptionPane.showMessageDialog(null, serverMessageError, "CityNet - Esborrar usuari", JOptionPane.ERROR_MESSAGE);
            
            //Si l'error és de sessió finalitzada...
            if (serverMessageError.equals("Not a valid token")) {
                
                //Tanquem l'aplicació
                System.exit(0);
                
            }
            
        }
        
        //Si s'ha canviat...
        if (serverMessageOK != null) {
            
            //Mostrem un missatge
            JOptionPane.showMessageDialog(null, serverMessageOK, "CityNet - Esborrar usuari", JOptionPane.INFORMATION_MESSAGE);
            //Tanquem el formulari
            this.dispose();
            
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelDetail;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPostCode;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTitlePersonalInfo;
    private javax.swing.JLabel lblUserAddress;
    private javax.swing.JLabel lblUserCity;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserPostalCode;
    private javax.swing.JLabel lblUserSurname;
    // End of variables declaration//GEN-END:variables
}
