package com.openfactorybeans.citynet.desktop.forms;

import com.openfactorybeans.citynet.desktop.users.UpdateUserRol;
import javax.swing.JTable;

/**
 * Formulari per canviar el rol d'un usuari
 * 
 * @author Jose
 */
public class UserUpdateRol extends javax.swing.JInternalFrame {

    //Definició de les variables per identificar el usuari que es vol canviar el rol
    String email, name, rol;
    
    /**
     * Creates new form UserUpdateRol
     */
    public UserUpdateRol(String email, String name, String rol) {
        initComponents();
        
        this.email = email;
        this.name = name;
        this.rol = rol;
        
        //Mostrem l'usuari i el seu rol actual
        lblTXTUserName.setText(this.name);
        lblTXTUserLevel.setText(this.rol);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDetail = new javax.swing.JPanel();
        lblTitlePersonalInfo = new javax.swing.JLabel();
        lblTXTUserName = new javax.swing.JLabel();
        lblOldUserLevel = new javax.swing.JLabel();
        lblTXTUserLevel = new javax.swing.JLabel();
        lblNewUserLevel = new javax.swing.JLabel();
        cbxUserLevel = new javax.swing.JComboBox<>();
        jPanelButtons = new javax.swing.JPanel();
        btnNewUserLevel = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        lblTitlePersonalInfo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitlePersonalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePersonalInfo.setText("Canviar rol usuari");
        lblTitlePersonalInfo.setPreferredSize(new java.awt.Dimension(0, 24));

        lblTXTUserName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTXTUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblOldUserLevel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblOldUserLevel.setText("Rol actual:");

        lblTXTUserLevel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblNewUserLevel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNewUserLevel.setText("Rol nou:");

        cbxUserLevel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbxUserLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuari", "Editor", "Admin" }));

        javax.swing.GroupLayout jPanelDetailLayout = new javax.swing.GroupLayout(jPanelDetail);
        jPanelDetail.setLayout(jPanelDetailLayout);
        jPanelDetailLayout.setHorizontalGroup(
            jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitlePersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTXTUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDetailLayout.createSequentialGroup()
                        .addComponent(lblOldUserLevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTXTUserLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDetailLayout.createSequentialGroup()
                        .addComponent(lblNewUserLevel)
                        .addGap(18, 18, 18)
                        .addComponent(cbxUserLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDetailLayout.setVerticalGroup(
            jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addComponent(lblTitlePersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTXTUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblOldUserLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTXTUserLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewUserLevel)
                    .addComponent(cbxUserLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnNewUserLevel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnNewUserLevel.setText("Canviar");
        btnNewUserLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserLevelActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setText("Cancel·lar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewUserLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewUserLevel)
                    .addComponent(btnCancel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelButtons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewUserLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserLevelActionPerformed

        //Obtenim els index del nou rol
        int rolIndex = cbxUserLevel.getSelectedIndex();
        switch (rolIndex) {
            case 0:
                rol = "user";
                break;
                
            case 1:
                rol = "editor";
                break;
                
            case 2:
                rol = "admin";
        }
        
        ////////////////////////////////////////////////////////////////////////////
        //Conectem amb el servidor per eliminar un usuari
        ////////////////////////////////////////////////////////////////////////////
        UpdateUserRol updateUserRol = new UpdateUserRol();
        updateUserRol.updateUserRol(UsersList.PUBLIC_URL, Login.token, email, rol);

        //Tanquem el formulari
        this.dispose();
    }//GEN-LAST:event_btnNewUserLevelActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        //Tanquem el formulari
        this.dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNewUserLevel;
    private javax.swing.JComboBox<String> cbxUserLevel;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelDetail;
    private javax.swing.JLabel lblNewUserLevel;
    private javax.swing.JLabel lblOldUserLevel;
    private javax.swing.JLabel lblTXTUserLevel;
    private javax.swing.JLabel lblTXTUserName;
    private javax.swing.JLabel lblTitlePersonalInfo;
    // End of variables declaration//GEN-END:variables
}
