/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openfactorybeans.citynet.desktop.forms;

import com.openfactorybeans.citynet.desktop.users.ListAllUsers;
import com.openfactorybeans.citynet.desktop.users.TMUser;
import com.openfactorybeans.citynet.desktop.users.User;
import com.openfactorybeans.citynet.desktop.utils.JsonUtils;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class UsersList extends javax.swing.JInternalFrame {

    //URL
    private static final String PUBLIC_URL = "http://ec2-35-180-7-53.eu-west-3.compute.amazonaws.com:8080/citynet/UserManager";
    
    //Variables finals de errors del servidor
    private final String NO_TOKEN = "No valid token";
    
    //Variables finals del combobox del filtre
    private final String ALL = "Tots";
    private final String USER = "User";
    private final String EDITOR = "Editor";
    private final String ADMIN = "Admin";
    
    //Declaració de variables pel llistat
    private ListAllUsers lau;
    private List<User> users;
    private TMUser model;
    private String serverResponse;
    private String listUsersJSon;
    
    //Variable que informa de la pàgina solicitada al servidor
    private int screen = 0;
    
    //Variable de finalització del llistat
    private boolean endList;
    
    /**
     * Creates new form UsersList
     */
    public UsersList() {
        initComponents();
        
        System.out.println("UsersList. " + Login.token);
        System.out.println("UsersList. " + Login.rol);
        

        ////////////////////////////////////////////////////////////////////////////
        //Conectem amb el servidor per obtenir els usuaris.
        ////////////////////////////////////////////////////////////////////////////
        lau = new ListAllUsers();
        serverResponse = lau.listAllUsers(PUBLIC_URL, screen, Login.token);
        
        //Mirem si el servidor ha retornat un error
        String serverMissage = JsonUtils.findJsonValue(serverResponse, "error");
        
        if (serverMissage.equals(NO_TOKEN)) {
            
            //No estem identificats
            JOptionPane.showMessageDialog(null, "No s'ha iniciat cap sessió", "Login", JOptionPane.ERROR_MESSAGE);
            
        } else {
        
            //Si són susaris
            listUsersJSon = serverResponse;

            //Passem el Json a ArrayList 
            users = new ArrayList<>();
            users = JsonUtils.parseJsonUser(listUsersJSon);

            //Comprovem les dades control
            endList = JsonUtils.parseJsonControl(listUsersJSon);

            //Cridem al mètode per canviar l'estat dels botons
            buttonsStates();

            //Omplim la taula amb l'Array
            fillTable();
            
        }

    }
    
    /**
     * Omple la taula per mostrar els usuaris a partir d'un Array
     */
    public void fillTable() {
        
        model = new TMUser(users);
        jTableUsers.setModel(model);
        
    }
    
    /**
     * Mètode per canviar l'estat dels botosn d'avanç i enrederir
     * segons les dades rebudes pel servidor
     */
    public void buttonsStates() {
        
        //Habilitem o deshabiitem el botó per enrederir
        if (screen == 0) {
            
            btnPageMinus.setEnabled(false);
            
        } else {
            
            btnPageMinus.setEnabled(true);
            
        }
        
        //Habilitem o deshabiitem el botó per avanç
        if (endList) {
            
            btnPagePlus.setEnabled(false);
            
        } else {
            
            btnPagePlus.setEnabled(true);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jPanelOptions = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelAvRe = new javax.swing.JPanel();
        btnPageMinus = new javax.swing.JButton();
        btnPagePlus = new javax.swing.JButton();
        jPanelFilter = new javax.swing.JPanel();
        cbxFilter = new javax.swing.JComboBox<>();
        btnFilter = new javax.swing.JButton();

        setClosable(true);
        setTitle("Llistat d'usuaris");

        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Email", "Nom", "Cognoms", "Adreça", "CP", "Població", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableUsers);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnPageMinus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPageMinus.setText("<<");
        btnPageMinus.setMaximumSize(new java.awt.Dimension(90, 35));
        btnPageMinus.setMinimumSize(new java.awt.Dimension(90, 35));
        btnPageMinus.setPreferredSize(new java.awt.Dimension(90, 35));
        btnPageMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPageMinusActionPerformed(evt);
            }
        });

        btnPagePlus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPagePlus.setText(">>");
        btnPagePlus.setMaximumSize(new java.awt.Dimension(90, 35));
        btnPagePlus.setMinimumSize(new java.awt.Dimension(90, 35));
        btnPagePlus.setPreferredSize(new java.awt.Dimension(90, 35));
        btnPagePlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagePlusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAvReLayout = new javax.swing.GroupLayout(jPanelAvRe);
        jPanelAvRe.setLayout(jPanelAvReLayout);
        jPanelAvReLayout.setHorizontalGroup(
            jPanelAvReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAvReLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPageMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagePlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAvReLayout.setVerticalGroup(
            jPanelAvReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAvReLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAvReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPageMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagePlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cbxFilter.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbxFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tots", "User", "Editor", "Admin" }));
        cbxFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFilterActionPerformed(evt);
            }
        });

        btnFilter.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnFilter.setText("Filtrar");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFilterLayout = new javax.swing.GroupLayout(jPanelFilter);
        jPanelFilter.setLayout(jPanelFilterLayout);
        jPanelFilterLayout.setHorizontalGroup(
            jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFilter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFilterLayout.setVerticalGroup(
            jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelOptionsLayout = new javax.swing.GroupLayout(jPanelOptions);
        jPanelOptions.setLayout(jPanelOptionsLayout);
        jPanelOptionsLayout.setHorizontalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAvRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOptionsLayout.setVerticalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanelOptionsLayout.createSequentialGroup()
                        .addGroup(jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelAvRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagePlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagePlusActionPerformed
        
        //Aumentem el número de pàgina per solicitar al servidor
        screen++;
        
        listUsersJSon = lau.listAllUsers(PUBLIC_URL, screen, Login.token);

        //Passem el Json a ArrayList 
        users = new ArrayList<>();
        users = JsonUtils.parseJsonUser(listUsersJSon);

        //Comprovem les dades control
        endList = JsonUtils.parseJsonControl(listUsersJSon);
        
        //Cridem al mètode per canviar l'estat dels botons
        buttonsStates();

        //Omplim la taula amb l'Array
        fillTable();
        
    }//GEN-LAST:event_btnPagePlusActionPerformed

    private void btnPageMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPageMinusActionPerformed
        
        //Aumentem el número de pàgina per solicitar al servidor
        screen--;
        
        listUsersJSon = lau.listAllUsers(PUBLIC_URL, screen, Login.token);

        //Passem el Json a ArrayList 
        users = new ArrayList<>();
        users = JsonUtils.parseJsonUser(listUsersJSon);

        //Comprovem les dades control
        endList = JsonUtils.parseJsonControl(listUsersJSon);
        
        //Cridem al mètode per canviar l'estat dels botons
        buttonsStates();

        //Omplim la taula amb l'Array
        fillTable();
    }//GEN-LAST:event_btnPageMinusActionPerformed

    private void cbxFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFilterActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        
        //Obtenim el index del item seleccionat del combobox
        String filter = cbxFilter.getSelectedItem().toString();
        
    }//GEN-LAST:event_btnFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnPageMinus;
    private javax.swing.JButton btnPagePlus;
    private javax.swing.JComboBox<String> cbxFilter;
    private javax.swing.JPanel jPanelAvRe;
    private javax.swing.JPanel jPanelFilter;
    private javax.swing.JPanel jPanelOptions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableUsers;
    // End of variables declaration//GEN-END:variables
}
